/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_example;

public class Library {
	
	public boolean isEvenNumber(int num) {
		return num % 2 == 0;
	}
	
	public int getLengthOfText(String str) {
		return str.length();
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
