/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {
    
	@Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertAll("Multiple Tests",
        		() -> assertEquals(true, classUnderTest.isEvenNumber(4)),
        		() -> assertEquals(3, classUnderTest.getLengthOfText("Hai"))
        		);
        System.out.println("Testing works");
    }
}
